server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: demo-kafka
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            type:
              mapping: gameDtoRequest:com.example.playground.model.request.GameDtoRequest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: gameDtoRequest:com.example.playground.model.request.GameDtoRequest
